export default {
  ada: {
    name: "Cardano",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  algo: {
    name: "Algorand",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  atom: {
    name: "Cosmos",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  bch: {
    name: "Bitcoin Cash",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  bsv: {
    name: "Bitcoin SV",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  btc: {
    name: "Bitcoin",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  dai: {
    name: "Dai",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  dash: {
    name: "Dash",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  dot: {
    name: "Polka",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  eos: {
    name: "EOS",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  etc: {
    name: "Ether classic",
    gradientStart: "#80ffea",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  eth: {
    name: "Ether",
    gradientStart: "#80ffea",
    gradientEnd: "#8aff80",
    decimalPrecision: 8,
  },
  etp: {
    name: "Metaverse",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  eur: {
    name: "Euro",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 2,
  },
  ftt: {
    name: "FTX Token",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  gbp: {
    name: "Pound Sterling",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 2,
  },
  iota: {
    name: "IOTA",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  jpy: {
    name: "Japanese Yen",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 0,
  },
  leo: {
    name: "Leocoin",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  link: {
    name: "Chainlink",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  ltc: {
    name: "Litecoin",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  neo: {
    name: "NEO",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  omg: {
    name: "OmiseGO",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  pnt: {
    name: "Eidoo",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  san: {
    name: "Santiment",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  trx: {
    name: "Tron",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  uni: {
    name: "Uniswap",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  usd: {
    name: "US Dollar",
    gradientStart: "#8aff80",
    gradientEnd: "#ffff80",
    decimalPrecision: 2,
  },
  usdt: {
    name: "USDt",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 2,
  },
  xaut: {
    name: "Tether Gold",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  xlm: {
    name: "Stellar",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  xmr: {
    name: "Monero",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  xrp: {
    name: "Ripple",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  xtz: {
    name: "Tezos",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  zec: {
    name: "Zcash",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
  zrx: {
    name: "0x",
    gradientStart: "#ffca80",
    gradientEnd: "#ffff80",
    decimalPrecision: 8,
  },
};
